# Generated by Django 5.0.2 on 2024-03-22 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD_APP', '0004_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='district',
        ),
    ]
