# Generated by Django 5.0.2 on 2024-04-29 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD_APP', '0009_alter_cart_cart_total_alter_order_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Delivered')], default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(choices=[(3, 'CLIENT'), (1, 'ADMIN')], default=1),
        ),
    ]
