# Generated by Django 5.0.2 on 2024-04-30 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD_APP', '0010_order_status_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'Cancelled'), (1, 'New'), (2, 'Pending'), (3, 'Delivered')], default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(choices=[(1, 'ADMIN'), (3, 'CLIENT')], default=1),
        ),
    ]
