# Generated by Django 5.0.2 on 2024-04-30 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD_APP', '0012_cart_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='status',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(choices=[(3, 'CLIENT'), (1, 'ADMIN')], default=1),
        ),
    ]
