# Generated by Django 5.0.2 on 2024-05-06 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD_APP', '0015_remove_item_quantity_alter_user_user_type_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(choices=[(1, 'ADMIN'), (3, 'CLIENT')], default=1),
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
